In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [11]:
data=pd.read_csv('train.csv')
data=np.array(data)
data_train=data.T
y_train=data_train[0]
x_train=data_train[1:]
x_train=x_train/255
x_train.shape


(784, 42000)

In [29]:
def init_params():
    W1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    W2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1,b1,W2,b2

def ReLU(z):
    return np.maximum(0,z)

def deri_ReLU(z):
    return (z>0).astype(float)

def Softmax(z):
    exp_z = np.exp(z - np.max(z, axis=0, keepdims=True))
    A = exp_z / np.sum(exp_z, axis=0, keepdims=True)
    return A

def one_hot(Y,num_classes=10):
    one_hot_Y = np.zeros((num_classes, Y.size))
    one_hot_Y[Y, np.arange(Y.size)] = 1
    return one_hot_Y

def forward_prop(W1,b1,W2,b2,x_train):
    z1=np.dot(W1,x_train)+b1
    A1=ReLU(z1)
    z2=np.dot(W2,A1)+b2
    A2=Softmax(z2)
    return z1,A1,z2,A2

def backward_prop(z1,A1,z2,A2,W1,W2,x_train,y_train):
    y=one_hot(y_train)
    dz2=A2-y #Size=(10,m)
    m=y.shape[1]
    #A1 size=(10,m)
    dw2=1/m*np.dot(dz2,A1.T)
    db2=1/m*np.sum(dz2,axis=1,keepdims=True)
    dz1=np.dot(W2.T,dz2)*deri_ReLU(z1)
    dw1=1/m*np.dot(dz1,x_train.T)
    db1=1/m*np.sum(dz1,axis=1,keepdims=True)
    return dw1,db1,dw2,db2

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,alpha):
    W1 = W1 - alpha*dW1
    b1 = b1 - alpha*db1
    W2 = W2 - alpha*dW2
    b2 = b2 - alpha*db2
    return W1,b1,W2,b2

def compute_loss(A2,y):
    Y = one_hot(y)
    m = Y.shape[1]
    eps = 1e-9
    A2 = np.clip(A2,eps,1-eps)
    loss = -np.sum(Y*np.log(A2))/m
    return loss

def predict(A2):
    return np.argmax(A2,axis=0)


In [30]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dw1, db1, dw2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dw1, db1, dw2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [31]:
W1, b1, W2, b2 = gradient_descent(x_train,y_train, 0.10, 500)

Iteration:  0
[2 2 2 ... 2 2 2] [1 0 1 ... 7 6 9]
0.11516666666666667
Iteration:  10
[4 0 1 ... 2 0 0] [1 0 1 ... 7 6 9]
0.21369047619047618
Iteration:  20
[4 0 1 ... 5 0 0] [1 0 1 ... 7 6 9]
0.31373809523809526
Iteration:  30
[2 0 1 ... 5 6 2] [1 0 1 ... 7 6 9]
0.3997380952380952
Iteration:  40
[1 0 1 ... 5 6 7] [1 0 1 ... 7 6 9]
0.4728333333333333
Iteration:  50
[1 0 1 ... 9 6 7] [1 0 1 ... 7 6 9]
0.5307142857142857
Iteration:  60
[1 0 1 ... 9 6 7] [1 0 1 ... 7 6 9]
0.5763095238095238
Iteration:  70
[1 0 1 ... 9 6 7] [1 0 1 ... 7 6 9]
0.6130952380952381
Iteration:  80
[1 0 1 ... 9 6 7] [1 0 1 ... 7 6 9]
0.6429523809523809
Iteration:  90
[1 0 1 ... 7 6 7] [1 0 1 ... 7 6 9]
0.6676190476190477
Iteration:  100
[1 0 1 ... 7 6 7] [1 0 1 ... 7 6 9]
0.6879047619047619
Iteration:  110
[1 0 1 ... 7 6 7] [1 0 1 ... 7 6 9]
0.7064761904761905
Iteration:  120
[1 0 1 ... 7 6 7] [1 0 1 ... 7 6 9]
0.7225
Iteration:  130
[1 0 1 ... 7 6 7] [1 0 1 ... 7 6 9]
0.7355238095238095
Iteration:  140
[1 0 1 ...